name: Mon action avec JavaScript et Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configuration du environnement
      uses: actions/setup-node@v2
      with:
        node-version: 18.13.0

    - name: Installation de Python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9

    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installation des dépendances Node
      run: npm ci

    - name: Installation des dépendances Python
      run: pip install -r requirements.txt

    - name: Exécution des tests Python
      run: python -m pytest

    - name: Build Node
      run: npm run build
      
    - name: Build Node
      run: npm install

    - name: Build Python
      run: python setup.py build
      
    - name: Npm start
      run: npm start
      

